Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    post 'admin/check-file'    => 'admin#checkFile'
    namespace :admin do
        root 'dashboard#index'
        resources :login, only: [:index]
        post 'check-login' => 'login#checkLogin'
        get 'logout' => 'login#logout'
        post 'refer-weather'                     => 'dashboard#referWeather'
        get 'dashboard'                          => 'dashboard#index'
        #--------------------------------------------------------
        get 'regist-courses'                     => 'registcourses#index'
        post 'regist-courses/search'             => 'registcourses#search'
        post 'regist-courses/update-status'      => 'registcourses#updateStatus'
        post 'regist-courses/delete'             => 'registcourses#delete'
        #--------------------------------------------------------
        get 'setting'                            => 'setting#index'
        post 'setting/refer-setting'             => 'setting#referSetting'
        post 'setting/update'                    => 'setting#update'
        post 'setting/update-trans'              => 'setting#updateTrans'
        #-----------------------------------------------------------
        get 'profile'                            => 'users#profile'
        post 'profile/changepass'                => 'users#changepass'
        get 'users'                              => 'users#index'
        get 'users/edit'                         => 'users#edit'
        get 'users/create'                       => 'users#create'
        post 'users/delete'                      => 'users#delete'
        post 'users/save-user'                   => 'users#saveUser'
        post 'users/update-user'                 => 'users#updateUser'
        post 'users/reset-pass'                  => 'users#resetPass'
        #-----------------------------------------------------------
        get 'courses'                            => 'courses#index'
        post 'courses/refer-course'              => 'courses#referCourse'
        post 'courses/refer-course-trans'        => 'courses#referCourseTrans'
        post 'courses/update-course'             => 'courses#updateCourse'
        post 'courses/update-course-trans'       => 'courses#updateCourseTrans'
        get 'courses/classes'                    => 'courses#classes'
        post 'courses/refer-classes'             => 'courses#referClasses'
        get 'courses/class'                      => 'courses#getClass'
        get 'courses/edit-class'                 => 'courses#editClass'
        post 'courses/refer-class-trans'         => 'courses#referClassTrans'
        post 'courses/save-class'                => 'courses#saveClass'
        post 'courses/update-class'              => 'courses#updateClassTrans'
        post 'courses/update-show-class'         => 'courses#updateShowClass'
        post 'courses/delete-class'              => 'courses#deleteClass'
        #-----------------------------------------------------------
        get 'letters'                            => 'letters#index'
        get 'letter/edit'                        => 'letters#edit'
        get 'letter/create'                      => 'letters#create'
        post 'letter/delete'                     => 'letters#delete'
        post 'letter/save-letter'                => 'letters#saveLetter'
        post 'letter/update-trans'               => 'letters#updateTrans'
        post 'letter/update-show'                => 'letters#updateShow'
        post 'letter/refer-letter'               => 'letters#referLetter'
        #-----------------------------------------------------------
        get 'regist-advisories'                  => 'registadvisories#index'
        post 'regist-advisories/search'          => 'registadvisories#search'
        post 'regist-advisories/update-status'   => 'registadvisories#updateStatus'
        post 'regist-advisories/delete'          => 'registadvisories#delete'
        #-----------------------------------------------------------
        get 'slides'                             => 'slides#index'
        get 'slides/create'                      => 'slides#create'
        get 'slides/edit'                        => 'slides#edit'
        post 'slides/update-show-slide'          => 'slides#updateShowSlide'
        post 'slides/save-slide'                 => 'slides#saveSlide'
        post 'slides/refer-slide'                => 'slides#referSlide'
        post 'slides/update-slide-trans'         => 'slides#updateSlideTrans'
        post 'slides/delete'                     => 'slides#delete'
        #-----------------------------------------------------------
        get 'media'                              => 'medias#index'
        get 'medias/create'                      => 'medias#create'
        get 'medias/edit'                        => 'medias#edit'
        post 'medias/delete'                     => 'medias#delete'
        post 'medias/save-media'                 => 'medias#saveMedia'
        #-----------------------------------------------------------
        get 'albums'                             => 'albums#index'
        get 'albums/add-photos'                  => 'albums#create'
        post 'albums/delete'                     => 'albums#delete'
        post 'albums/save-photos'                => 'albums#savePhotos'
        #-----------------------------------------------------------
        get 'differents'                         => 'differents#index'
        get 'differents/create'                  => 'differents#create'
        get 'differents/edit'                    => 'differents#edit'
        post 'differents/delete'                 => 'differents#delete'
        post 'differents/update-show-different'  => 'differents#updateShowDifferent'
        post 'differents/update-different-trans' => 'differents#updateDifferentTrans'
        post 'differents/save-different'         => 'differents#saveDifferent'
        post 'differents/refer-different'        => 'differents#referDifferent'
        post 'differents/delete'                 => 'differents#delete'
        #-----------------------------------------------------------
        get 'questions'                          => 'questions#index'
        get 'questions/create'                   => 'questions#create'
        get 'questions/edit'                     => 'questions#edit'
        post 'questions/delete'                  => 'questions#delete'
        post 'questions/save-questions'          => 'questions#saveQuestion'
        post 'questions/update-question-trans'   => 'questions#updateQuestionTrans'
        post 'questions/delete'                  => 'questions#delete'
        post 'questions/refer-question'          => 'questions#referQuestion'
        #-----------------------------------------------------------
        get 'events'                             => 'events#index'
        get 'events/create'                      => 'events#create'
        get 'events/edit'                        => 'events#edit'
        post 'events/update-show-event'          => 'events#updateShowEvent'
        post 'events/delete'                     => 'events#delete'
        post 'events/delete-thumb-image'         => 'events#deleteThumbImage'
        post 'events/save-event'                 => 'events#saveEvent'
        post 'events/update-events-trans'        => 'events#updateEventTrans'
        post 'events/refer-event'                => 'events#referEvent'
        post 'events/save-photos'                => 'events#savePhotos'
        #-----------------------------------------------------------
        get 'regist-events'                      => 'registevents#index'
        post 'regist-events/search'              => 'registevents#search'
        post 'regist-events/update-status'       => 'registevents#updateStatus'
        post 'regist-events/delete'              => 'registevents#delete'
        #-----------------------------------------------------------
        get 'subscribes'                         => 'subscribes#index'
        post 'subscribes/search'                 => 'subscribes#search'
        post 'subscribes/update-status'          => 'subscribes#updateStatus'
        post 'subscribes/delete'                 => 'subscribes#delete'
    end
end
