class CreateQuestions < ActiveRecord::Migration[5.1]
    def self.up
        create_table :questions, id: false do |t|
            t.column :id,           :int,         :limit      => 10,    :null => false
            t.column :lang,         :string,      :limit      => 5,     :null => false
            t.column :question,     :string,      :limit      => 500,   :null => false
            t.column :answer,       :string,      :limit      => 1000,  :null => false
            t.column :created_at,   :datetime,    :null       => false
            t.column :created_by,   :string,      :limit      => 10
            t.column :updated_at,   :datetime
            t.column :updated_by,   :string,      :limit      => 10
            t.column :deleted_at,   :datetime
            t.column :deleted_by,   :string,      :limit      => 10
        end
        execute "ALTER TABLE questions ADD PRIMARY KEY (id,lang);"
        Question.create :id => 1, :lang => 'vi', :question => 'BrSE School là trường đào tạo BrSE, SE cho thị trường Nhật Bản, vậy cách thức đào tạo tiếng Nhật khác với các trung tâm Nhật ngữ như thế nào.', :answer => 'Trung tâm đào tạo Nhật ngữ sẽ giảng dạy tiếng Nhật phổ thông còn BrSE School chú trọng đào tạo tiếng Nhật về chuyên ngành IT và đặc biệt là giao tiếp.'
        Question.create :id => 1, :lang => 'ja', :question => 'BrSE School là trường đào tạo BrSE, SE cho thị trường Nhật Bản, vậy cách thức đào tạo tiếng Nhật khác với các trung tâm Nhật ngữ như thế nào.', :answer => 'Trung tâm đào tạo Nhật ngữ sẽ giảng dạy tiếng Nhật phổ thông còn BrSE School chú trọng đào tạo tiếng Nhật về chuyên ngành IT và đặc biệt là giao tiếp.'
        Question.create :id => 1, :lang => 'en', :question => 'BrSE School là trường đào tạo BrSE, SE cho thị trường Nhật Bản, vậy cách thức đào tạo tiếng Nhật khác với các trung tâm Nhật ngữ như thế nào.', :answer => 'Trung tâm đào tạo Nhật ngữ sẽ giảng dạy tiếng Nhật phổ thông còn BrSE School chú trọng đào tạo tiếng Nhật về chuyên ngành IT và đặc biệt là giao tiếp.'
        Question.create :id => 2, :lang => 'vi', :question => 'Làm thế nào để sau khi tốt nghiệp học viên có thể làm việc được ngay trong công ty Nhật.', :answer => 'Trong chương trình giảng dạy sẽ có các dự án mà học viên tham gia với vai trò BrSE, SE và làm việc với các kỹ sư Nhật. Các dự án này sẽ giúp học viên làm quen với công việc thực tế ở các công ty Nhật. Ngoài ra học viên còn được đào tạo business manner, các kỹ năng mềm khác để có thể quen với phong cách làm việc của người Nhật.'
        Question.create :id => 2, :lang => 'ja', :question => 'Làm thế nào để sau khi tốt nghiệp học viên có thể làm việc được ngay trong công ty Nhật.', :answer => 'Trong chương trình giảng dạy sẽ có các dự án mà học viên tham gia với vai trò BrSE, SE và làm việc với các kỹ sư Nhật. Các dự án này sẽ giúp học viên làm quen với công việc thực tế ở các công ty Nhật. Ngoài ra học viên còn được đào tạo business manner, các kỹ năng mềm khác để có thể quen với phong cách làm việc của người Nhật.'
        Question.create :id => 2, :lang => 'en', :question => 'Làm thế nào để sau khi tốt nghiệp học viên có thể làm việc được ngay trong công ty Nhật.', :answer => 'Trong chương trình giảng dạy sẽ có các dự án mà học viên tham gia với vai trò BrSE, SE và làm việc với các kỹ sư Nhật. Các dự án này sẽ giúp học viên làm quen với công việc thực tế ở các công ty Nhật. Ngoài ra học viên còn được đào tạo business manner, các kỹ năng mềm khác để có thể quen với phong cách làm việc của người Nhật.'
        Question.create :id => 3, :lang => 'vi', :question => 'Để có thể xin vào làm việc tại các công ty thị trường Nhật và làm việc tại Nhật Bản thì cần phải đáp ứng những điều kiện nào. BrSE School có hỗ trợ gì hay không.', :answer => 'Học viên cần hoàn thành khóa học của trường để có những kỹ năng cần thiết làm việc cho thị trường Nhật Bản. BrSE School đào tạo cho học viên các kỹ năng khi đi xin việc, phỏng vấn để có thể tự tin trước các nhà tuyển dụng. Ngoài ra, sau khi tốt nghiệp học viên có cơ hội thực tập 3 tháng tại công ty ANS ở Tokyo, Nhật Bản. Đây là môi trường thực tế giúp học viên nâng cao trình độ bản thân để có thể làm việc được ngay tại Nhật. Trong quá trình thực tập học viên sẽ được giới thiệu việc làm với các công ty Nhật khác.'
        Question.create :id => 3, :lang => 'ja', :question => 'Để có thể xin vào làm việc tại các công ty thị trường Nhật và làm việc tại Nhật Bản thì cần phải đáp ứng những điều kiện nào. BrSE School có hỗ trợ gì hay không.', :answer => 'Học viên cần hoàn thành khóa học của trường để có những kỹ năng cần thiết làm việc cho thị trường Nhật Bản. BrSE School đào tạo cho học viên các kỹ năng khi đi xin việc, phỏng vấn để có thể tự tin trước các nhà tuyển dụng. Ngoài ra, sau khi tốt nghiệp học viên có cơ hội thực tập 3 tháng tại công ty ANS ở Tokyo, Nhật Bản. Đây là môi trường thực tế giúp học viên nâng cao trình độ bản thân để có thể làm việc được ngay tại Nhật. Trong quá trình thực tập học viên sẽ được giới thiệu việc làm với các công ty Nhật khác.'
        Question.create :id => 3, :lang => 'en', :question => 'Để có thể xin vào làm việc tại các công ty thị trường Nhật và làm việc tại Nhật Bản thì cần phải đáp ứng những điều kiện nào. BrSE School có hỗ trợ gì hay không.', :answer => 'Học viên cần hoàn thành khóa học của trường để có những kỹ năng cần thiết làm việc cho thị trường Nhật Bản. BrSE School đào tạo cho học viên các kỹ năng khi đi xin việc, phỏng vấn để có thể tự tin trước các nhà tuyển dụng. Ngoài ra, sau khi tốt nghiệp học viên có cơ hội thực tập 3 tháng tại công ty ANS ở Tokyo, Nhật Bản. Đây là môi trường thực tế giúp học viên nâng cao trình độ bản thân để có thể làm việc được ngay tại Nhật. Trong quá trình thực tập học viên sẽ được giới thiệu việc làm với các công ty Nhật khác.'
        Question.create :id => 4, :lang => 'vi', :question => 'Có thể vừa học tại BrSE School vừa tham gia làm part time tại ANS ASIA được không?', :answer => 'Nếu học viên có năng lực và mong muốn làm việc tại công ty thì có thể tham gia vào các đợt tuyển dụng của công ty. Học viên đạt yêu cầu và phù hợp với vị trí công ty đang tuyển thì có thể vừa học vừa làm part time.'
        Question.create :id => 4, :lang => 'ja', :question => 'Có thể vừa học tại BrSE School vừa tham gia làm part time tại ANS ASIA được không?', :answer => 'Nếu học viên có năng lực và mong muốn làm việc tại công ty thì có thể tham gia vào các đợt tuyển dụng của công ty. Học viên đạt yêu cầu và phù hợp với vị trí công ty đang tuyển thì có thể vừa học vừa làm part time.'
        Question.create :id => 4, :lang => 'en', :question => 'Có thể vừa học tại BrSE School vừa tham gia làm part time tại ANS ASIA được không?', :answer => 'Nếu học viên có năng lực và mong muốn làm việc tại công ty thì có thể tham gia vào các đợt tuyển dụng của công ty. Học viên đạt yêu cầu và phù hợp với vị trí công ty đang tuyển thì có thể vừa học vừa làm part time.'
        Question.create :id => 5, :lang => 'vi', :question => 'Chỉ được học tại Việt Nam hay vừa học tại Việt Nam vừa học tại Nhật Bản?', :answer => 'Chương trình đào tạo bao gồm 10 tháng học tại Việt Nam và 3 tháng tham gia thực tế, làm việc, xin việc tại Nhật Bản. Chi phí sinh hoạt 3 tháng tại Nhật sẽ do học viên tự túc chi trả, công ty sẽ tạo điều kiện giúp đỡ học viên tìm chỗ ở và tạo môi trường làm việc thực tập tại Nhật Bản.'
        Question.create :id => 5, :lang => 'ja', :question => 'Chỉ được học tại Việt Nam hay vừa học tại Việt Nam vừa học tại Nhật Bản?', :answer => 'Chương trình đào tạo bao gồm 10 tháng học tại Việt Nam và 3 tháng tham gia thực tế, làm việc, xin việc tại Nhật Bản. Chi phí sinh hoạt 3 tháng tại Nhật sẽ do học viên tự túc chi trả, công ty sẽ tạo điều kiện giúp đỡ học viên tìm chỗ ở và tạo môi trường làm việc thực tập tại Nhật Bản.'
        Question.create :id => 5, :lang => 'en', :question => 'Chỉ được học tại Việt Nam hay vừa học tại Việt Nam vừa học tại Nhật Bản?', :answer => 'Chương trình đào tạo bao gồm 10 tháng học tại Việt Nam và 3 tháng tham gia thực tế, làm việc, xin việc tại Nhật Bản. Chi phí sinh hoạt 3 tháng tại Nhật sẽ do học viên tự túc chi trả, công ty sẽ tạo điều kiện giúp đỡ học viên tìm chỗ ở và tạo môi trường làm việc thực tập tại Nhật Bản.'
    end
    def self.down
        drop_table :questions
    end
end
